language: node_js
node_js:
  - "12"

jobs:
  include:
    - stage: Test
      script:
        - yarn typecheck
        - yarn test
    - stage: Build
      script:
        - STATIC_COMPRESS=true && yarn build

cache:
  yarn: true
