language: node_js
sudo: required
node_js:
  - "10"

before_install:
  # Repo for Yarn
  #- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  #- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  #- sudo apt-get update -qq
  #- sudo apt-get install -y -qq yarn
  - npm install -g codecov

jobs:
  #allow_failures:
  #  - stage: Lint

  include:
    - stage: Test
      script:
        - yarn tsc
        - yarn test:coverage
      after_success:
        - codecov
    - stage: Build
      script:
        - cp .travis/.env.travis.dist ./.env.production.local
        - yarn build
    - stage: Lint
      script:
        - yarn lint

cache:
  yarn: true
